# Generated by Django 4.0.3 on 2022-06-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=20)),
                ('costo_curso', models.IntegerField()),
                ('comision_curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('apellido_usuario', models.CharField(max_length=20)),
                ('nombre_user', models.CharField(max_length=20)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('tel_usuario', models.IntegerField()),
                ('direccion_usuario', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('curso_usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
