# Generated by Django 4.0.3 on 2022-06-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder01App', '0002_usuario_foto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='foto_curso',
            field=models.ImageField(blank='', default='', upload_to='images/'),
        ),
    ]
