# Generated by Django 4.0.3 on 2022-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder01App', '0003_cursos_foto_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_noticia', models.CharField(max_length=20)),
                ('noticia', models.CharField(max_length=1500)),
                ('descripcion_noticia', models.CharField(max_length=200)),
                ('imagen_noticia', models.ImageField(blank='', default='', upload_to='images/')),
            ],
        ),
    ]
