# Generated by Django 4.0.3 on 2022-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder01App', '0005_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='descripcion_curso',
            field=models.CharField(blank='', default='', max_length=500),
        ),
    ]
